module.exports = {
    eventos: {
        id: 'eventos',
        title: 'Eventos de dança',
        titleExtension: 'para adicionar em sua agenda',
        mainDescription: '<p>Aqui você fica sabendo dos eventos organizados pelo Espaço Luana Pinheiro ou com participação de nossos alunos, professores, amigos e parceiros.</p>',
        photos: [
            // REFERENCIA DE FORMATO - NÃO APAGAR
            // {
            //     id: 'orient-star-festival',
            //     title: 'Orient Star Festival - 3ª edição',
            //     date: '<span class="highlight">25</span> & <span class="highlight">26</span> Mai às 8h30',
            //     dateId: '2019-05-26 19:00',
            //     imgSrc: 'eventos/orient-star-3edicao.jpg',
            //     imgAlt: 'Orient Star Festival - 3ª edição',
            //     url: 'https://www.facebook.com/events/530078820746850/',
            //     external: true,
            // },
            // {
            //     id: 'festa-cerejeira-34',
            //     title: '34ª Festa da Cerejeira',
            //     date: '<span class="highlight">14</span> Jul / Dom às 17h',
            //     dateId: '2019-07-14',
            //     imgSrc: 'eventos/festa-cerejeira-34.jpg',
            //     imgAlt: '34ª Festa da Cerejeira',
            //     url: 'https://www.facebook.com/espacoartisticoluanapinheiro/photos/a.400315673439784/1418098818328126/?type=3&theater',
            //     external: true,
            // },
            // {
            //     id: '33a-festa-das-nacoes',
            //     title: '33ª Festa das naçoes',
            //     date: '<span class="highlight">07</span> & <span class="highlight">08</span> Set / SAB & DOM',
            //     dateId: '2019-09-07',
            //     imgSrc: 'eventos/33a-festa-das-nacoes.jpg',
            //     imgAlt: '33ª Festa das naçoes',
            //     url: 'https://www.diariodesuzano.com.br/caderno-d/33a-edicao-da-festa-das-nacoes-acontece/49867/',
            //     external: true,
            // },
            // {
            //     id: '2-encontro-sp-belly-dance',
            //     title: '2° Encontro São Paulo Belly Dance',
            //     date: '<span class="highlight">15</span> Set / DOM às 14h00',
            //     dateId: '2019-09-15',
            //     imgSrc: 'eventos/2-encontro-sp-belly-dance.jpg',
            //     imgAlt: '2° Encontro São Paulo Belly Dance',
            //     url: 'https://www.facebook.com/espacoartisticoluanapinheiro/photos/a.400315673439784/1433985066739501/?type=3&theater',
            //     external: true,
            // },
            // {
            //     id: 'outubro-rosa-2019',
            //     title: 'Outubro Rosa',
            //     date: '<span class="highlight">06</span> Out / Dom às 15h',
            //     dateId: '2019-10-06',
            //     imgSrc: 'eventos/outubro-rosa-2019.jpg?v=2',
            //     imgAlt: 'Outubro Rosa',
            //     url: 'https://www.facebook.com/events/211334263087528/?ti=icl',
            //     external: true,
            // },
            // {
            //     id: 'bwa-nov-2019',
            //     title: 'Master Class Bellyworks Argentina',
            //     date: '<span class="highlight">02</span> NOV / Sáb 11h às 15h',
            //     dateId: '2019-11-02 15:00',
            //     imgSrc: 'eventos/bwa-nov-2019.jpg',
            //     imgAlt: 'Master Class Bellyworks Argentina',
            //     url: 'https://www.facebook.com/BellyWorksArgentina/photos/a.1849668448670023/2132106427092889/?type=3&theater',
            //     external: true,
            // },
            // {
            //     id: 'feira-artes-gastronomia-2019',
            //     title: 'Feira de artes, gastronomia e moda',
            //     date: '<span class="highlight">19</span>, <span class="highlight">20</span> & <span class="highlight">21</span>/ Nov',
            //     dateId: '2019-11-20',
            //     imgSrc: 'eventos/feira-artes-gastronomia-2019.jpg',
            //     imgAlt: 'Feira de artes, gastronomia e moda',
            //     url: 'https://www.facebook.com/photo.php?fbid=2617773314953002&id=100001610782852&set=a.123671347696557&source=57&ref=content_filter',
            //     external: true,
            // },
            // {
            //     id: 'orient-star-2020',
            //     title: 'Orient Star Festival 2020',
            //     date: '<span class="highlight">23</span> & <span class="highlight">24</span>/ Mai',
            //     dateId: '2020-05-23 15:00',
            //     imgSrc: 'eventos/orient-star-2020.jpg',
            //     imgAlt: 'Orient Star Festival 2020',
            //     url: 'https://www.facebook.com/orientstarfestival/',
            //     external: true,
            // },
            {
                id: 'audicoes-2020',
                title: 'Audições 2020',
                date: '<span class="highlight">13</span> à <span class="highlight">24</span>/ Jan',
                dateId: '2020-01-13 13:00',
                imgSrc: 'eventos/audicoes-2020.jpg',
                imgAlt: 'Audições 2020',
                url: 'https://www.facebook.com/espacoartisticoluanapinheiro/photos/a.400315673439784/1589585824512757/?type=3&theater',
                external: true,
            },
            {
                id: 'uma-viagem-ao-oriente',
                title: 'Oásis · uma viagem ao oriente',
                date: '<span class="highlight">01</span> Dez / DOM às 18h30',
                dateId: '2019-12-01 15:00',
                imgSrc: 'eventos/uma-viagem-ao-oriente.jpg',
                imgAlt: 'Oásis · uma viagem ao oriente',
                url: 'https://www.facebook.com/events/467227767180806/',
                external: true,
            },
            {
                id: 'meu-ballet-de-repertorio',
                title: 'Meu Ballet de Repertório',
                date: '<span class="highlight">01</span> Dez / DOM às 15h',
                dateId: '2019-12-01 15:00',
                imgSrc: 'eventos/meu-ballet-de-repertorio.jpg',
                imgAlt: '18º Espetáculo de Dança - Meu Ballet de Repertório',
                url: 'https://www.facebook.com/events/467227767180806/',
                external: true,
            }
        ]
    }
};
